apiVersion: apps/v1
kind: Deployment
metadata:
  name: xnet-node-app
spec:
  selector:
    matchLabels:
      app: xnet-node-app
  replicas: 1
  template:
    metadata:
      labels:
        app: xnet-node-app
    spec:
      containers:
        - name: xnet-node-app
          image: ghcr.io/nextnet-works/xnet:0.1.1
          env:
          - name: SEEDS
            value: "2a0c32c085713a5a2e1619cb4ab789cadbf2cdbf@54.177.136.249:26656"
          - name: PERSISTENT_PEERS
            value: "2a0c32c085713a5a2e1619cb4ab789cadbf2cdbf@54.177.136.249:26656"
          - name: CHAIN_ID
            value: "xnet_03012023-1"
          - name: MINIMUM_GAS_PRICES
            value: 0.025uxnet
          - name: PRUNING
            value: nothing
          - name: MONIKER
            value: mynode
          - name: XNETD_HOME
            value: "/.xnetd"
          ports:
            - containerPort: 26656